# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e80748355ddf6c6fc4d0027dd93c3462bcc93426bd94718d928f59fde71a989d114254622cf1511b9d1af1bfc661fa6a166f26e36255e7e8a60891dd4a3aedef

test:
  secret_key_base: 649281f11af35bd1f6db60b2758036a2761b7fc1db377cf38c14b15a84b71d5a6f583b859858a8ac1875c9e969a64c9edb8f4d12e6c8347a11809a9df9c8d5c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
